wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.10
    start_time: 1664882243
    t:
      1:
      - 1
      - 5
      4: 3.8.10
      5: 0.12.1
      8:
      - 1
      - 2
      - 5
adamw:
  desc: null
  value:
    lr: 0.001
    weight_decay: 0.0001
batch_size:
  desc: null
  value: 64
device:
  desc: null
  value: cpu
epochs:
  desc: null
  value: 500
eval_steps:
  desc: null
  value: 100
log_steps:
  desc: null
  value: 20
max_grad_norm:
  desc: null
  value: 3.0
model:
  desc: null
  value:
    edge_dim: 1
    embedding_dim: 64
    n_encoders: 3
    node_dim: 64
    num_classes: 100
random_state:
  desc: null
  value: 42
run_evaluation:
  desc: null
  value: true
scheduler:
  desc: null
  value:
    anneal_strategy: linear
    max_lr: 0.001
    pct_start: 0.1
    total_steps: 27000
total_steps:
  desc: null
  value: 27000
wandb:
  desc: null
  value:
    entity: broccoliman
    project: Dvoryanin
